services:
  postgres:
    image: postgres
    restart: always
    container_name: bookstorepostgresdb
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: bookstoresa
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - bookstore_postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network
  bookstore-api:
    restart: always
    build:
      context: .
      dockerfile: ./BookStoreServer/BookStoreServer.WebApi/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5050:8080"
      - "5051:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=bookstore;Username=bookstoresa;Password=${POSTGRES_PASSWORD}
    networks:
      - bookstore-network
  bookstore-client:
    restart: always
    build:
      context: .
      dockerfile: ./BookStoreClient/Dockerfile
    ports:
      - "5052:80"
    networks:
      - bookstore-network
networks:
  bookstore-network:
    driver: bridge
volumes:
  bookstore_postgres_data:
